"""Results page, recap CSV and README recap for a game config."""
import csv
import json
from pathlib import Path

import numpy as np

from blackjack.counts import SYSTEMS
from blackjack.engine import HAND_LABELS
from blackjack.qlearn import QTable
from blackjack.solver import InfiniteDeckSolver

TEMPLATE = Path(__file__).with_name("report_template.html")
STANDALONE_HEAD = ('<!doctype html>\n<html lang="en">\n<meta charset="utf-8">\n'
                   '<meta name="viewport" content="width=device-width, initial-scale=1">\n')
UPS = list(range(2, 11)) + [1]
ROWS_TWO = [f"H{t}" for t in range(5, 21)] + [f"S{t}" for t in range(13, 21)] \
    + ["2,2", "3,3", "4,4", "5,5", "6,6", "7,7", "8,8", "9,9", "10,10", "A,A"]
ROWS_MULTI = [f"H{t}" for t in range(12, 21)] + [f"S{t}" for t in range(13, 21)]
RECAP_START, RECAP_END = "<!-- recap:start -->", "<!-- recap:end -->"
# money in units won per 100 rounds dealt (1 unit = the minimum bet), except the last column
RECAP_COLUMNS = ["system", "type", "flat_bet_per_100_rounds", "count_play_gain_per_100_rounds",
                 "share_of_rounds_with_edge", "bet_1_3_per_100_rounds", "bet_0_3_per_100_rounds",
                 "bet_0_3_per_100_hands_played"]
SEAT_COLUMNS = ["system", "seat", "flat_bet_per_100_rounds", "flat_bet_std_error",
                "bet_1_3_per_100_rounds", "bet_0_3_per_100_rounds"]
NOTE = ("All money is in units won per 100 rounds dealt (1 unit = the minimum bet), except the last "
        "column: units won per 100 hands actually played, since 0–3 sits out the rounds without a "
        "player edge (\"rounds with player edge\" gives how many are played). Betting: 3 units at "
        "counts with a player edge, otherwise 1 (1–3) or nothing (0–3). Generated by `scripts/run.py`.")


def _r4(x):
    return None if np.isnan(x) else round(float(x), 4)


def _cells(Q, N, rows, two):
    return [[{"q": [_r4(x) for x in Q[u - 1, HAND_LABELS.index(r), two]],
              "n": [int(x) for x in N[u - 1, HAND_LABELS.index(r), two]]} for u in UPS] for r in rows]


def _best_action(Q, rows, two):
    out = []
    for r in rows:
        row = []
        for u in UPS:
            q = Q[u - 1, HAND_LABELS.index(r), two]
            row.append(-1 if np.all(np.isnan(q)) else int(np.where(np.isnan(q), -np.inf, q).argmax()))
        out.append(row)
    return out


def index_plays(qt):
    """Per (hand, up, change): the count where the deviation from count-blind play starts."""
    labels = [qt.buckets.label(k) for k in range(qt.buckets.n)]
    centers = qt.buckets.centers()
    mode = int(np.argmax(qt.N.sum(axis=(1, 2, 3, 4))))
    first = {}
    for lbl, hand, up, a0, a1, _ in qt.deviations():
        b = labels.index(lbl)
        if b == mode:
            continue
        side = 1 if b > mode else -1
        key = (hand, up, a0, a1, side)
        if key not in first or (b < first[key] if side > 0 else b > first[key]):
            first[key] = b
    plays = [dict(hand=h, up=u, frm=a0, to=a1, side=sd, label=labels[b], center=float(centers[b]))
             for (h, u, a0, a1, sd), b in first.items()]
    plays.sort(key=lambda d: (d["side"], d["side"] * d["center"], d["hand"]))
    ins = qt.insurance_index()
    if ins:
        k = labels.index(ins)
        plays.insert(0, dict(hand="Insurance", up="A", frm="decline", to="insure", side=1, label=ins,
                             center=float(centers[k])))
    return plays, mode


def build(cfg):
    """Write docs/<game>/strategy_card.html and docs/<game>/summary.csv from results/<game>/."""
    basic = json.loads((cfg.results_dir / "basic_strategy.json").read_text())["ev"]
    systems, summary, betting = {}, [], {}
    for name in cfg.systems:
        qt = QTable.load(cfg.results_dir / f"q_{name}.npz")
        bet = json.loads((cfg.results_dir / f"betting_{name}.json").read_text())
        betting[name] = dict(labels=bet["labels"], strategies=bet["strategies"])
        Qp, pooled = qt.policy_Q(), qt.pooled_Q()
        plays, mode = index_plays(qt)
        share, edge, se = map(np.array, (bet["share"], bet["edge"], bet["edge_se"]))
        flat = bet["strategies"]["flat 1"]
        systems[name] = dict(
            desc=SYSTEMS[name].description, balanced=SYSTEMS[name].balanced, tags=list(SYSTEMS[name].tags),
            labels=bet["labels"], centers=qt.buckets.centers().tolist(), mode=mode,
            # one entry per count bucket, then the count-blind (all counts pooled) table
            two=[_cells(Qp[b], qt.N[b], ROWS_TWO, 1) for b in range(qt.buckets.n)]
                + [_cells(pooled, qt.N.sum(axis=0), ROWS_TWO, 1)],
            multi=[_cells(Qp[b], qt.N[b], ROWS_MULTI, 0) for b in range(qt.buckets.n)]
                + [_cells(pooled, qt.N.sum(axis=0), ROWS_MULTI, 0)],
            base_two=_best_action(pooled, ROWS_TWO, 1), base_multi=_best_action(pooled, ROWS_MULTI, 0),
            edge=dict(labels=bet["labels"], share=share.tolist(), mean=edge.tolist(), se=se.tolist(),
                      overall=flat["ev_round"], overall_se=float(np.sqrt((share ** 2 * se ** 2).sum()))),
            devs=plays)
        summary.append(dict(name=name, balanced=SYSTEMS[name].balanced, flat=flat["ev_round"],
                            se=systems[name]["edge"]["overall_se"], share=float(share[edge > 0].sum()),
                            gain=flat["ev_round"] - basic,
                            won13=100 * bet["strategies"]["1-3 max EV"]["ev_round"],
                            won03=100 * bet["strategies"]["0-3 max EV"]["ev_round"],
                            ev_hand03=bet["strategies"]["0-3 max EV"]["ev_hand"], seats=bet["seats"]))

    rules = cfg.rules
    solver = InfiniteDeckSolver(rules)
    dp = solver.q_table()
    data = dict(
        title=cfg.title, rounds=cfg.rounds, eval_rounds=cfg.eval_rounds,
        rules={k: getattr(rules, k) for k in rules.__dataclass_fields__},
        ups=["A" if u == 1 else str(u) for u in UPS], rows2=ROWS_TWO, rowsm=ROWS_MULTI,
        dp_two=[[[_r4(x) for x in dp[u - 1, HAND_LABELS.index(r), 1]] for u in UPS] for r in ROWS_TWO],
        dp_multi=[[[_r4(x) for x in dp[u - 1, HAND_LABELS.index(r), 0]] for u in UPS] for r in ROWS_MULTI],
        dp_round_ev=solver.round_ev(), basic_ev=basic, summary=summary, systems=systems, betting=betting,
        seats={s["name"]: s["seats"] for s in summary})

    cfg.docs_dir.mkdir(parents=True, exist_ok=True)
    page = (TEMPLATE.read_text(encoding="utf-8").replace("/*TITLE*/", f"Counting Strategies, {cfg.title}")
            .replace("/*DATA*/null", json.dumps(data, separators=(",", ":"))))
    (cfg.docs_dir / "strategy_card.html").write_text(STANDALONE_HEAD + page + "</html>\n", encoding="utf-8")
    _write_csv(summary, basic, cfg.docs_dir / "summary.csv")
    _write_seats_csv(summary, cfg.docs_dir / "by_seat.csv")


def _units(x, decimals):
    return "" if x in ("", None) else f"{float(x):+.{decimals}f}".replace("-", "−")


def _write_csv(summary, basic, path):
    rows = []
    for s in sorted(summary, key=lambda s: -s["won03"]):
        name, kind = SYSTEMS[s["name"]].description.split(", ", 1)
        rows.append(dict(zip(RECAP_COLUMNS, [name, kind, 100 * s["flat"], 100 * s["gain"], s["share"],
                                             s["won13"], s["won03"], 100 * s["ev_hand03"]])))
    rows.append(dict(zip(RECAP_COLUMNS, ["No count", "basic strategy", 100 * basic, 0.0])))
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=RECAP_COLUMNS)
        w.writeheader()
        for r in rows:
            w.writerow({k: (f"{v:.6f}" if isinstance(v, float) else v) for k, v in r.items()})


def _write_seats_csv(summary, path):
    """Results by seat, 1 = first to act."""
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=SEAT_COLUMNS)
        w.writeheader()
        for s in sorted(summary, key=lambda s: -s["won03"]):
            for i, seat in enumerate(s["seats"]):
                w.writerow(dict(zip(SEAT_COLUMNS, [SYSTEMS[s["name"]].description.split(", ")[0], i + 1]
                                    + [f"{v:.6f}" for v in (100 * seat["flat"], 100 * seat["se"],
                                                            seat["won13"], seat["won03"])])))


def _seat_table(cfg, system):
    path = cfg.docs_dir / "by_seat.csv"
    if not path.exists():
        return []
    with open(path, encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if r["system"] == system]
    if len(rows) < 2:
        return []
    lines = ["", f"By seat, {system} (seat 1 acts first; each seat sees the cards of the seats before it):", "",
             "| seat | flat bet | bet 1–3, play every round | bet 0–3, sit out bad counts |",
             "|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['seat']} | {_units(r['flat_bet_per_100_rounds'], 3)} ± {float(r['flat_bet_std_error']):.3f} "
                     f"| {_units(r['bet_1_3_per_100_rounds'], 2)} | {_units(r['bet_0_3_per_100_rounds'], 2)} |")
    return lines


def _recap_table(cfg):
    lines = [f"### {cfg.title}", "",
             f"[Results page](docs/{cfg.name}/strategy_card.html) · [CSV](docs/{cfg.name}/summary.csv)", "",
             "| system | type | flat bet | gain from playing the count | rounds with player edge "
             "| bet 1–3, play every round | bet 0–3, sit out bad counts | 0–3: units won per 100 hands played |",
             "|---|---|---|---|---|---|---|---|"]
    with open(cfg.docs_dir / "summary.csv", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        share = f"{float(r['share_of_rounds_with_edge']) * 100:.1f}%" if r["share_of_rounds_with_edge"] else ""
        lines.append(f"| {r['system']} | {r['type']} | {_units(r['flat_bet_per_100_rounds'], 3)} "
                     f"| {_units(r['count_play_gain_per_100_rounds'], 3)} | {share} "
                     f"| {_units(r['bet_1_3_per_100_rounds'], 2)} | {_units(r['bet_0_3_per_100_rounds'], 2)} "
                     f"| {_units(r['bet_0_3_per_100_hands_played'], 2)} |")
    return lines + _seat_table(cfg, rows[0]["system"])


def _games_table(configs, link=lambda cfg: f"docs/{cfg.name}/strategy_card.html"):
    """One line per game: its best count system (by the 0-3 return) against no count."""
    lines = ["| game | best count | no count, flat bet | best count, flat bet "
             "| bet 1–3, play every round | bet 0–3, sit out bad counts | 0–3: units won per 100 hands played |",
             "|---|---|---|---|---|---|---|"]
    for cfg in configs:
        with open(cfg.docs_dir / "summary.csv", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        best, basic = rows[0], rows[-1]
        lines.append(f"| [{cfg.title}]({link(cfg)}) | {best['system']} "
                     f"| {_units(basic['flat_bet_per_100_rounds'], 2)} | {_units(best['flat_bet_per_100_rounds'], 2)} "
                     f"| {_units(best['bet_1_3_per_100_rounds'], 2)} | {_units(best['bet_0_3_per_100_rounds'], 2)} "
                     f"| {_units(best['bet_0_3_per_100_hands_played'], 2)} |")
    return lines


def update_readme(configs, path="README.md"):
    """Rewrite the README recap (between the recap markers) for every config with a summary.csv."""
    path = Path(path)
    text = path.read_text(encoding="utf-8")
    if RECAP_START not in text:
        return False
    configs = [c for c in configs if (c.docs_dir / "summary.csv").exists()]
    lines = [RECAP_START, NOTE, ""] + _games_table(configs) + [""]
    for cfg in configs:
        lines += _recap_table(cfg) + [""]
    lines += [RECAP_END]
    start, end = text.index(RECAP_START), text.index(RECAP_END) + len(RECAP_END)
    path.write_text(text[:start] + "\n".join(lines) + text[end:], encoding="utf-8")
    return True
